name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # اجرا هر روز در نیمه‌شب UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Ensure dist directory exists
        run: mkdir -p dist

      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: Shayan-02
          svg_out_path: dist/github-contribution-grid-snake.svg
          gif_out_path: dist/github-contribution-grid-snake.gif

      - name: Upload Snake Animation
        uses: actions/upload-artifact@v4
        with:
          name: snake-animation
          path: dist

      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          mkdir -p output
          mv dist/github-contribution-grid-snake.svg output/ || exit 1

          git add output/github-contribution-grid-snake.svg

          if git diff --cached --quiet; then
            echo "No changes to commit"
            exit 0
          fi

          git commit -m "Update Snake Animation"
          git push origin main
